"""Canonical serialisation and re-lock stability (PRO-110).

Stability is the requirement, not a nicety: the lock is committed, so a file that
shows up dirty after every build is one reviewers learn to skip. Each test here
guards a different way that can break.
"""

import pytest

from prompticorn.artifact import ArtifactId, PinnedArtifact
from prompticorn.content import UnitId
from prompticorn.lockfile import (
    LockedArtifact,
    LockedOutput,
    LockedUnit,
    LockFile,
    LockReader,
    LockWriter,
)

DIGEST_A = "a" * 64
DIGEST_B = "b" * 64
STAMP = "2026-08-09T02:40:00Z"
LATER = "2026-12-25T11:11:11Z"


def make_lock(resolved_at: str = STAMP, *, reverse: bool = False) -> LockFile:
    """A populated lock, optionally assembled in reverse order.

    The reversal is the point: a caller building entries in discovery order and
    one building them backwards must produce the same file.
    """
    artifacts = [
        LockedArtifact(PinnedArtifact(ArtifactId.parse("acme/sec@2.1.0"), DIGEST_A), source="acme"),
        LockedArtifact(PinnedArtifact(ArtifactId.parse("local/agent.code@0.0.0"), DIGEST_B)),
    ]
    units = [
        LockedUnit(UnitId.parse("skill/threat-modeling/minimal"), "builtin", DIGEST_A),
        LockedUnit(UnitId.parse("agent/code"), "builtin", DIGEST_B),
    ]
    outputs = [LockedOutput("z/last.md", DIGEST_A), LockedOutput("a/first.md", DIGEST_B)]
    if reverse:
        artifacts, units, outputs = artifacts[::-1], units[::-1], outputs[::-1]
    return LockFile("0.5.0", resolved_at, tuple(artifacts), tuple(units), tuple(outputs))


# ── AC 1 / AC 2: the file does not depend on how it was assembled ─────────────


def test_assembly_order_does_not_affect_the_file() -> None:
    """AC 2: reordering the manifest must not reorder the lock."""
    assert LockWriter.render(make_lock()) == LockWriter.render(make_lock(reverse=True))


def test_rendering_is_deterministic() -> None:
    assert LockWriter.render(make_lock()) == LockWriter.render(make_lock())


@pytest.mark.parametrize(
    ("section", "key"), [("artifacts", "identity"), ("units", "id"), ("outputs", "path")]
)
def test_sequences_are_sorted_by_their_defined_key(section: str, key: str) -> None:
    rendered = LockWriter.render(make_lock(reverse=True))
    values = [
        line.split(f"{key}:", 1)[1].strip()
        for line in rendered.splitlines()
        if f"{key}:" in line and line.lstrip().startswith(("- ", f"{key}:"))
    ]

    assert values == sorted(values), f"{section} is not sorted by {key}"


def test_mapping_keys_are_sorted() -> None:
    """Readability is traded for stability here, deliberately."""
    top_level = [
        line.split(":", 1)[0]
        for line in LockWriter.render(make_lock()).splitlines()
        if line and not line.startswith(("#", " ", "-"))
    ]

    assert top_level == sorted(top_level)


def test_no_anchors_or_aliases_are_emitted() -> None:
    """PyYAML aliases any object it has already written.

    That would make the file's shape depend on object identity in the writer's
    memory — something neither a reader nor a diff should be able to observe.
    """
    shared = PinnedArtifact(ArtifactId.parse("acme/sec@2.1.0"), DIGEST_A)
    lock = LockFile(
        "0.5.0",
        STAMP,
        artifacts=(
            LockedArtifact(shared, source="one"),
            LockedArtifact(shared, source="two"),
        ),
    )

    rendered = LockWriter.render(lock)

    assert "&id" not in rendered
    assert "*id" not in rendered
    assert rendered.count(DIGEST_A) == 2, "the digest must be written out both times"


def test_long_digests_are_never_folded() -> None:
    """A folded scalar makes the bytes depend on nesting depth."""
    rendered = LockWriter.render(make_lock())

    for line in rendered.splitlines():
        if DIGEST_A in line or DIGEST_B in line:
            assert line.rstrip().endswith(("a" * 8, "b" * 8))


def test_the_file_says_not_to_edit_it() -> None:
    rendered = LockWriter.render(make_lock())

    assert rendered.startswith("# Generated by prompticorn. Do not edit.")


# ── AC 1: resolved_at preservation ─────────────────────────────────────────────


def test_writing_twice_produces_a_byte_identical_file(tmp_path) -> None:
    """AC 1, and the reason `resolved_at` is preserved rather than stamped."""
    path = tmp_path / ".prompticorn" / "prompticorn.lock"

    assert LockWriter.write(make_lock(), path) is True
    first = path.read_bytes()
    assert LockWriter.write(make_lock(LATER), path) is False

    assert path.read_bytes() == first


def test_resolved_at_is_preserved_when_nothing_else_changed(tmp_path) -> None:
    path = tmp_path / "prompticorn.lock"
    LockWriter.write(make_lock(), path)

    LockWriter.write(make_lock(LATER), path)

    assert STAMP in path.read_text(encoding="utf-8")
    assert LATER not in path.read_text(encoding="utf-8")


def test_reassembling_in_a_different_order_is_still_a_no_op(tmp_path) -> None:
    """Order must not masquerade as a real re-resolution."""
    path = tmp_path / "prompticorn.lock"
    LockWriter.write(make_lock(), path)

    assert LockWriter.write(make_lock(LATER, reverse=True), path) is False


def test_a_real_change_advances_resolved_at(tmp_path) -> None:
    """The other half of the rule — preservation must not become staleness."""
    path = tmp_path / "prompticorn.lock"
    LockWriter.write(make_lock(), path)

    changed = make_lock(LATER)
    changed = LockFile(
        changed.prompticorn_version,
        changed.resolved_at,
        changed.artifacts,
        changed.units + (LockedUnit(UnitId.parse("agent/ask"), "builtin", DIGEST_A),),
        changed.outputs,
    )

    assert LockWriter.write(changed, path) is True
    assert LATER in path.read_text(encoding="utf-8")


@pytest.mark.parametrize(
    "mutate",
    [
        pytest.param(
            lambda lock: LockFile(
                "9.9.9", lock.resolved_at, lock.artifacts, lock.units, lock.outputs
            ),
            id="prompticorn_version",
        ),
        pytest.param(
            lambda lock: LockFile(
                lock.prompticorn_version,
                lock.resolved_at,
                lock.artifacts,
                lock.units,
                lock.outputs + (LockedOutput("new.md", DIGEST_A),),
            ),
            id="outputs",
        ),
        pytest.param(
            lambda lock: LockFile(
                lock.prompticorn_version,
                lock.resolved_at,
                lock.artifacts[:1],
                lock.units,
                lock.outputs,
            ),
            id="artifacts",
        ),
    ],
)
def test_every_recorded_field_counts_as_a_change(tmp_path, mutate) -> None:
    """A field that silently failed to trigger a rewrite would go stale unnoticed."""
    path = tmp_path / "prompticorn.lock"
    LockWriter.write(make_lock(), path)

    assert LockWriter.write(mutate(make_lock(LATER)), path) is True


def test_writing_creates_the_parent_directory(tmp_path) -> None:
    path = tmp_path / "nested" / "deeper" / "prompticorn.lock"

    LockWriter.write(make_lock(), path)

    assert path.is_file()


def test_a_corrupt_existing_lock_is_overwritten_not_fatal(tmp_path) -> None:
    """Refusing would leave the user stuck with the broken file."""
    path = tmp_path / "prompticorn.lock"
    path.write_text("this is not: [valid lock", encoding="utf-8")

    assert LockWriter.write(make_lock(), path) is True
    assert LockReader.read(path).resolved_at == STAMP


# ── AC 4: round-trip ───────────────────────────────────────────────────────────


def test_read_then_write_is_unchanged() -> None:
    """AC 4: the lock survives a full parse and re-render."""
    rendered = LockWriter.render(make_lock())

    assert LockWriter.render(LockReader.parse(rendered, "test")) == rendered


def test_an_empty_lock_round_trips() -> None:
    empty = LockFile("0.5.0", STAMP)
    rendered = LockWriter.render(empty)

    assert LockReader.parse(rendered, "test") == empty
