"""Canonical serialisation of the lock (PRO-110).

Stability is the requirement. A committed generated file that churns is a review
tax, and one that always shows up dirty stops being read. Three mechanisms hold
the line, and each guards a different failure:

- **Sorted keys and sequences.** Enumeration order must never reach the file.
  Sequence order is defined by :meth:`LockFile.canonical`; key order is the
  dumper's ``sort_keys``.
- **No aliases.** PyYAML emits ``&id001``/``*id001`` whenever one object appears
  twice. Two artifacts sharing a digest object would serialise as an anchor and a
  reference — unreadable, and unstable under reordering. The dumper refuses
  aliases outright, and the model hands over freshly built mappings as a second
  line of defence.
- **``resolved_at`` preserved.** Advanced only on a real re-resolution, so a
  no-op re-lock leaves the file byte-identical rather than dirtying the tree on
  every build.
"""

from __future__ import annotations

from dataclasses import replace
from pathlib import Path
from typing import Any

import yaml

from prompticorn.lockfile.lock_file import LockFile

# Wide enough that no scalar is ever folded. A 64-character digest under a nested
# key exceeds PyYAML's default width of 80, and a folded scalar makes the bytes
# depend on how deeply nested the value happens to be.
_LINE_WIDTH = 4096

_HEADER = "# Generated by prompticorn. Do not edit.\n# Regenerate with `prompticorn lock`.\n"


class _NoAliasDumper(yaml.SafeDumper):
    """A dumper that never emits anchors or aliases.

    PyYAML's default behaviour is to alias any object it has already written.
    That is correct YAML and wrong for a lock: it makes the file's shape depend
    on object identity in the writer's memory, which is not something a reader —
    or a diff — should ever be able to observe.
    """

    def ignore_aliases(self, data: Any) -> bool:
        return True


class LockWriter:
    """Renders a :class:`LockFile` to its canonical bytes."""

    @staticmethod
    def render(lock: LockFile) -> str:
        """The canonical text of a lock.

        Deterministic for a given value: two equal locks render identically,
        regardless of how either was assembled.
        """
        body = yaml.dump(
            lock.to_mapping(),
            Dumper=_NoAliasDumper,
            sort_keys=True,
            default_flow_style=False,
            allow_unicode=True,
            width=_LINE_WIDTH,
        )
        return _HEADER + body

    @classmethod
    def write(cls, lock: LockFile, path: Path) -> bool:
        """Write the lock, preserving ``resolved_at`` when nothing else changed.

        This is what makes a no-op re-lock a no-op. Without it the timestamp
        advances on every write and the file is dirty after every build, which
        is precisely how a committed lock becomes noise that reviewers skip.

        An unreadable or absent existing file is treated as "no previous lock"
        rather than an error: this method's job is to produce a correct lock, and
        refusing to overwrite a corrupt one would leave the user stuck with it.

        Args:
            lock: The freshly resolved lock.
            path: Where to write it.

        Returns:
            True if the file's contents changed, False if it was already
            byte-identical. Callers use this to report "already up to date"
            without diffing the file themselves.
        """
        existing = cls._read_existing(path)
        if existing is not None and existing.equals_ignoring_resolved_at(lock):
            # `replace` rather than a field-by-field rebuild: a new field added to
            # the model must not be silently dropped here, which is exactly what
            # an explicit constructor call would do.
            lock = replace(lock, resolved_at=existing.resolved_at)

        rendered = cls.render(lock)
        if path.exists() and path.read_text(encoding="utf-8") == rendered:
            return False

        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(rendered, encoding="utf-8")
        return True

    @staticmethod
    def _read_existing(path: Path) -> LockFile | None:
        """The lock already at ``path``, or None if there is nothing usable."""
        from prompticorn.lockfile.errors import LockError
        from prompticorn.lockfile.lock_reader import LockReader

        if not path.exists():
            return None
        try:
            return LockReader.read(path)
        except LockError:
            return None
