<!-- path: sync.sh -->
#!/usr/bin/env bash
# sync.sh
# Rebuilds the kilo/ and cline/ directory structures from the flat/ source files.
# Run this after editing any file in flat/.
#
# Usage:
#   ./sync.sh                  # rebuild both kilo/ and cline/
#   ./sync.sh --kilo-only      # rebuild kilo/ only
#   ./sync.sh --cline-only     # rebuild cline/ only
#   ./sync.sh --dry-run        # show what would be copied without doing it

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FLAT="$SCRIPT_DIR/flat"
KILO="$SCRIPT_DIR/kilo"
CLINE="$SCRIPT_DIR/cline"

DRY_RUN=false
DO_KILO=true
DO_CLINE=true

for arg in "$@"; do
  case $arg in
    --dry-run)   DRY_RUN=true ;;
    --kilo-only) DO_CLINE=false ;;
    --cline-only) DO_KILO=false ;;
  esac
done

copy() {
  local src="$1"
  local dst="$2"
  if [ ! -f "$src" ]; then
    echo "  MISSING SOURCE: $src" >&2
    return 1
  fi
  if $DRY_RUN; then
    echo "  [dry-run] cp $src → $dst"
  else
    mkdir -p "$(dirname "$dst")"
    cp "$src" "$dst"
    echo "  ✓ $(basename "$src") → ${dst#$SCRIPT_DIR/}"
  fi
}

# ─────────────────────────────────────────────
# KILO STRUCTURE
# .kilocode/rules/          → always loaded (all modes)
# .kilocode/rules-architect/ → Architect mode
# .kilocode/rules-code/      → Code mode
# .kilocode/rules-review/    → Review mode
# .kilocode/rules-debug/     → Debug mode
# .kilocode/rules-ask/       → Ask mode
# .kilocode/rules-orchestrator/ → Orchestrator mode
# ─────────────────────────────────────────────
if $DO_KILO; then
  echo ""
  echo "▶ Building kilo/"

  # Always-on rules (every mode)
  copy "$FLAT/core-system.md"               "$KILO/.kilocode/rules/core-system.md"
  copy "$FLAT/core-conventions.md"          "$KILO/.kilocode/rules/core-conventions.md"

  # Architect mode
  copy "$FLAT/architect-scaffold.md"        "$KILO/.kilocode/rules-architect/scaffold.md"
  copy "$FLAT/architect-task-breakdown.md"  "$KILO/.kilocode/rules-architect/task-breakdown.md"
  copy "$FLAT/architect-data-model.md"      "$KILO/.kilocode/rules-architect/data-model.md"

  # Code mode
  copy "$FLAT/code-feature.md"              "$KILO/.kilocode/rules-code/feature.md"
  copy "$FLAT/code-boilerplate.md"          "$KILO/.kilocode/rules-code/boilerplate.md"
  copy "$FLAT/code-house-style.md"          "$KILO/.kilocode/rules-code/house-style.md"
  copy "$FLAT/code-refactor.md"             "$KILO/.kilocode/rules-code/refactor.md"
  copy "$FLAT/code-migration.md"            "$KILO/.kilocode/rules-code/migration.md"
  copy "$FLAT/code-dependency-upgrade.md"   "$KILO/.kilocode/rules-code/dependency-upgrade.md"

  # Review mode
  copy "$FLAT/review-code.md"               "$KILO/.kilocode/rules-review/code-review.md"
  copy "$FLAT/review-performance.md"        "$KILO/.kilocode/rules-review/performance.md"
  copy "$FLAT/review-accessibility.md"      "$KILO/.kilocode/rules-review/accessibility.md"

  # Debug mode
  copy "$FLAT/debug-root-cause.md"          "$KILO/.kilocode/rules-debug/root-cause.md"
  copy "$FLAT/debug-log-analysis.md"        "$KILO/.kilocode/rules-debug/log-analysis.md"
  copy "$FLAT/debug-rubber-duck.md"         "$KILO/.kilocode/rules-debug/rubber-duck.md"

  # Ask mode
  copy "$FLAT/ask-docs.md"                  "$KILO/.kilocode/rules-ask/docs.md"
  copy "$FLAT/ask-testing.md"               "$KILO/.kilocode/rules-ask/testing.md"
  copy "$FLAT/ask-decision-log.md"          "$KILO/.kilocode/rules-ask/decision-log.md"

  # Orchestrator mode
  copy "$FLAT/orchestrator-devops.md"       "$KILO/.kilocode/rules-orchestrator/devops.md"
  copy "$FLAT/orchestrator-meta.md"         "$KILO/.kilocode/rules-orchestrator/meta.md"

  echo "  ✓ Kilo structure complete"
fi

# ─────────────────────────────────────────────
# CLINE STRUCTURE
# .clinerules  → single file, always loaded
# All prompt content is concatenated into one file with section headers.
# ─────────────────────────────────────────────
if $DO_CLINE; then
  echo ""
  echo "▶ Building cline/"

  CLINE_RULES="$CLINE/.clinerules"

  if $DRY_RUN; then
    echo "  [dry-run] Generating $CLINE_RULES from flat/ files"
  else
    mkdir -p "$CLINE"

    {
      echo "# .clinerules"
      echo "# Auto-generated by sync.sh — edit files in flat/ then re-run sync.sh"
      echo "# Last synced: $(date '+%Y-%m-%d %H:%M')"
      echo ""

      for section in \
        "CORE BEHAVIORS:core-system.md" \
        "CONVENTIONS:core-conventions.md" \
        "PLANNING / ARCHITECT:architect-scaffold.md" \
        "TASK BREAKDOWN:architect-task-breakdown.md" \
        "DATA MODEL:architect-data-model.md" \
        "FEATURE IMPLEMENTATION:code-feature.md" \
        "BOILERPLATE:code-boilerplate.md" \
        "HOUSE STYLE:code-house-style.md" \
        "REFACTORING:code-refactor.md" \
        "MIGRATION:code-migration.md" \
        "DEPENDENCY UPGRADE:code-dependency-upgrade.md" \
        "CODE REVIEW:review-code.md" \
        "PERFORMANCE REVIEW:review-performance.md" \
        "ACCESSIBILITY REVIEW:review-accessibility.md" \
        "DEBUGGING:debug-root-cause.md" \
        "LOG ANALYSIS:debug-log-analysis.md" \
        "RUBBER DUCK:debug-rubber-duck.md" \
        "DOCUMENTATION:ask-docs.md" \
        "TESTING:ask-testing.md" \
        "DECISION LOG:ask-decision-log.md" \
        "DEVOPS:orchestrator-devops.md" \
        "META / PROCESS:orchestrator-meta.md"
      do
        label="${section%%:*}"
        file="${section##*:}"
        src="$FLAT/$file"
        if [ -f "$src" ]; then
          echo "---"
          echo "## $label"
          echo ""
          # Strip the filename header comment (first 2 lines) to avoid redundancy
          tail -n +3 "$src"
          echo ""
        else
          echo "## $label — MISSING SOURCE: $file" >&2
        fi
      done
    } > "$CLINE_RULES"

    echo "  ✓ .clinerules generated ($(wc -l < "$CLINE_RULES") lines)"
  fi
fi

echo ""
echo "Done."
if $DRY_RUN; then echo "(dry run — no files written)"; fi
