"""CodexBuilder for generating OpenAI Codex CLI configuration (PRO-16).

Codex reads ``AGENTS.md`` (always-on, via E1) and Agent Skills from
``.agents/skills/`` (via E2) — the same surfaces as Zed. So v1 emits each agent
as a skill (``.agents/skills/<slug>/SKILL.md``), rides the root ``AGENTS.md`` for
conventions + routing, and adds a ``.codex/config.toml`` — a real Codex config
layer that also serves as the unique marker distinguishing a Codex project from
a Zed one (Zed never emits ``.codex/``).

Verified against openai/codex (codex-rs). Native ``[agents.roles]`` + MCP are a
follow-up. See the Codex design doc in Linear.
"""

import yaml

from prompticorn.builders.base import Builder, BuildOptions
from prompticorn.builders.errors import BuilderValidationError
from prompticorn.builders.roo_builder import slugify
from prompticorn.ir.models import Agent

# Codex caps the total skill catalog description budget; keep each one tight.
_MAX_DESCRIPTION = 500


class CodexBuilder(Builder):
    """Builder for Codex agent-as-skill files (frontmatter + Markdown body)."""

    def build(self, agent: Agent, options: BuildOptions, config: dict | None = None) -> str:
        """Build one ``.agents/skills/<slug>/SKILL.md`` body for an agent."""
        errors = self.validate(agent)
        if errors:
            raise BuilderValidationError(
                errors=errors, message=f"Invalid agent '{agent.name}': {'; '.join(errors)}"
            )
        description = " ".join(agent.description.split())
        if len(description) > _MAX_DESCRIPTION:
            description = description[: _MAX_DESCRIPTION - 1].rstrip() + "…"
        frontmatter = yaml.safe_dump(
            {"name": slugify(agent.name), "description": description},
            sort_keys=False,
            allow_unicode=True,
        ).strip()
        return f"---\n{frontmatter}\n---\n\n{agent.system_prompt}\n"

    def validate(self, agent: Agent) -> list[str]:
        """Validate an Agent for Codex (name, description, system prompt required)."""
        errors = []
        if not agent.name:
            errors.append("Agent name is required and must not be empty")
        if not agent.description:
            errors.append("Agent description is required and must not be empty")
        if not agent.system_prompt:
            errors.append("System prompt is required and must not be empty")
        return errors

    def get_output_format(self) -> str:
        """Return a description of the Codex output format."""
        return "Codex agent-as-skill (.agents/skills/) + .codex/config.toml"

    def get_tool_name(self) -> str:
        """Return the internal tool name."""
        return "codex"


def generate_codex_config() -> str:
    """Return minimal ``.codex/config.toml`` content.

    Safe, non-opinionated defaults (no pinned model). Also the unique project
    marker that distinguishes a Codex project from a Zed one.
    """
    return (
        "# Generated by prompticorn. Codex reads AGENTS.md for conventions\n"
        "# and .agents/skills/ for reusable skills.\n"
        'approval_policy = "on-request"\n'
        'sandbox_mode = "workspace-write"\n'
    )
