"""Capture a setup, reproduce it elsewhere (PRO-132).

`TestTheDefiningProperty` is the milestone's reason to exist, made executable:
save a profile from one project, apply it to an empty directory, build both, and
compare every generated byte. If a manifest key were missing from the portable
set, the two trees would differ — which is a far better signal than a unit test
asserting that a list of key names is the list of key names.
"""

from __future__ import annotations

from pathlib import Path

import pytest
import yaml

from prompticorn.config_handler import ConfigHandler
from prompticorn.profiles import (
    FileProfileStore,
    InvalidProfileError,
    ProfileNotFoundError,
    ProfileService,
)
from prompticorn.prompt_builder import get_prompt_builder

NOW = "2026-09-12T12:00:00Z"

MANIFEST = {
    "version": "2.0",
    "repository": {"type": "single-language"},
    "spec": {"language": "python", "runtime": "3.14", "package_manager": "uv"},
    "variant": "verbose",
    "active_personas": ["software_engineer", "qa_tester"],
    "ai_tool": "claude",
}


def make_project(root: Path, manifest: dict) -> Path:
    config = root / ".prompticorn"
    config.mkdir(parents=True)
    (config / ".prompticorn.yaml").write_text(yaml.safe_dump(manifest), encoding="utf-8")
    return root


def built_tree(root: Path, tool: str) -> dict[str, bytes]:
    """Build a project's output and return it keyed by relative path."""
    config = ConfigHandler.load_config(root / ".prompticorn" / ".prompticorn.yaml")
    output = root / "generated"
    output.mkdir(exist_ok=True)
    get_prompt_builder(tool).build(output, config, dry_run=False)
    return {
        path.relative_to(output).as_posix(): path.read_bytes()
        for path in sorted(output.rglob("*"))
        if path.is_file()
    }


@pytest.fixture
def service(tmp_path: Path) -> ProfileService:
    return ProfileService(store=FileProfileStore(root=tmp_path / "profiles"))


@pytest.fixture
def source(tmp_path: Path) -> Path:
    return make_project(tmp_path / "source", MANIFEST)


class TestTheDefiningProperty:
    def test_apply_reproduces_the_source_projects_output_exactly(
        self, service: ProfileService, source: Path, tmp_path: Path
    ):
        """The milestone's headline claim. Two projects, one profile, identical
        generated bytes."""
        service.save_from_repo("backend", source, "house standard", NOW)
        fresh = tmp_path / "fresh"
        fresh.mkdir()

        service.apply("backend", fresh)

        assert built_tree(fresh, "claude") == built_tree(source, "claude")

    def test_a_missing_portable_key_would_be_caught_by_that_comparison(
        self, service: ProfileService, source: Path, tmp_path: Path
    ):
        """Guards the premise above. If `variant` did not travel, the trees
        differ — which is why the test compares output rather than key names."""
        service.save_from_repo("backend", source, "", NOW)
        fresh = tmp_path / "fresh"
        fresh.mkdir()
        service.apply("backend", fresh)

        make_project(tmp_path / "minimal", {**MANIFEST, "variant": "minimal"})

        assert built_tree(fresh, "claude") != built_tree(tmp_path / "minimal", "claude")


class TestSave:
    def test_capturing_stores_the_manifest(self, service: ProfileService, source: Path):
        profile = service.save_from_repo("backend", source, "house standard", NOW)

        assert profile.payload["spec"]["language"] == "python"
        assert profile.description == "house standard"

    def test_capturing_twice_produces_two_versions(self, service: ProfileService, source: Path):
        service.save_from_repo("backend", source, "", NOW)

        assert service.save_from_repo("backend", source, "", NOW).version == 2

    def test_capturing_a_project_with_no_manifest_raises(
        self, service: ProfileService, tmp_path: Path
    ):
        bare = tmp_path / "bare"
        bare.mkdir()

        with pytest.raises(ProfileNotFoundError):
            service.save_from_repo("backend", bare, "", NOW)

    def test_the_payload_is_ordered_by_the_portable_key_list(
        self, service: ProfileService, tmp_path: Path
    ):
        """Two captures of one project must produce the same payload however
        either manifest happened to be written."""
        forward = make_project(tmp_path / "a", MANIFEST)
        backward = make_project(tmp_path / "b", dict(reversed(list(MANIFEST.items()))))

        one = service.save_from_repo("one", forward, "", NOW)
        two = service.save_from_repo("two", backward, "", NOW)

        assert list(one.payload) == list(two.payload)
        assert one.digest() == two.digest()


class TestApply:
    def test_applying_writes_the_manifest(self, service: ProfileService, source: Path, tmp_path):
        service.save_from_repo("backend", source, "", NOW)
        fresh = tmp_path / "fresh"
        fresh.mkdir()

        outcome = service.apply("backend", fresh)

        assert outcome.written
        assert (fresh / ".prompticorn" / ".prompticorn.yaml").is_file()

    def test_applying_reports_what_changed(self, service: ProfileService, source: Path, tmp_path):
        service.save_from_repo("backend", source, "", NOW)
        target = make_project(tmp_path / "target", {**MANIFEST, "variant": "minimal"})

        outcome = service.apply("backend", target)

        assert outcome.had_existing
        assert "variant" in outcome.diff.render()

    def test_applying_to_a_matching_project_changes_nothing(
        self, service: ProfileService, source: Path
    ):
        service.save_from_repo("backend", source, "", NOW)

        assert service.apply("backend", source).changed_nothing

    def test_an_older_version_can_be_applied(self, service: ProfileService, source: Path, tmp_path):
        service.save_from_repo("backend", source, "", NOW)
        make_project(tmp_path / "changed", {**MANIFEST, "variant": "minimal"})
        service.save_from_repo("backend", tmp_path / "changed", "", NOW)
        fresh = tmp_path / "fresh"
        fresh.mkdir()

        service.apply("backend", fresh, version=1)

        assert ConfigHandler.load_config(
            fresh / ".prompticorn" / ".prompticorn.yaml"
        )["variant"] == "verbose"

    def test_an_unknown_profile_raises(self, service: ProfileService, tmp_path: Path):
        with pytest.raises(ProfileNotFoundError):
            service.apply("never-saved", tmp_path)


class TestDryRun:
    def test_dry_run_writes_nothing_at_all(self, service: ProfileService, source: Path, tmp_path):
        """Asserted by filesystem snapshot rather than by checking one file —
        a dry run that created a directory is still a dry run that wrote."""
        service.save_from_repo("backend", source, "", NOW)
        fresh = tmp_path / "fresh"
        fresh.mkdir()
        before = sorted(p.relative_to(fresh).as_posix() for p in fresh.rglob("*"))

        outcome = service.apply("backend", fresh, dry_run=True)

        assert not outcome.written
        assert sorted(p.relative_to(fresh).as_posix() for p in fresh.rglob("*")) == before

    def test_dry_run_still_reports_the_diff(self, service: ProfileService, source: Path, tmp_path):
        service.save_from_repo("backend", source, "", NOW)
        fresh = tmp_path / "fresh"
        fresh.mkdir()

        assert not service.apply("backend", fresh, dry_run=True).diff.is_empty

    def test_dry_run_does_not_overwrite_an_existing_manifest(
        self, service: ProfileService, source: Path, tmp_path
    ):
        service.save_from_repo("backend", source, "", NOW)
        target = make_project(tmp_path / "target", {**MANIFEST, "variant": "minimal"})

        service.apply("backend", target, dry_run=True)

        assert ConfigHandler.load_config(
            target / ".prompticorn" / ".prompticorn.yaml"
        )["variant"] == "minimal"


class TestValidation:
    def test_an_invalid_payload_fails_before_any_file_is_touched(
        self, service: ProfileService, tmp_path: Path
    ):
        """A project left holding a half-applied manifest is worse off than one
        where the command refused."""
        service.store.save("broken", {"artifacts": "not a list"}, "", NOW)
        fresh = tmp_path / "fresh"
        fresh.mkdir()

        with pytest.raises(InvalidProfileError):
            service.apply("broken", fresh)

        assert not (fresh / ".prompticorn").exists()

    def test_an_invalid_payload_does_not_damage_an_existing_manifest(
        self, service: ProfileService, tmp_path: Path
    ):
        service.store.save("broken", {"artifacts": "not a list"}, "", NOW)
        target = make_project(tmp_path / "target", MANIFEST)

        with pytest.raises(InvalidProfileError):
            service.apply("broken", target)

        assert ConfigHandler.load_config(
            target / ".prompticorn" / ".prompticorn.yaml"
        )["variant"] == "verbose"


class TestMigration:
    def test_a_profile_from_an_older_schema_migrates_on_apply(
        self, service: ProfileService, tmp_path: Path
    ):
        """Routing through ConfigHandler is what buys this: the established
        in-place migrations run, rather than a second path that could disagree
        with them."""
        service.store.save(
            "legacy",
            {"version": "1.0", "repository": {"type": "single-language"},
             "spec": {"language": "python"}, "variant": "minimal", "ai_tool": "claude"},
            "",
            NOW,
        )
        fresh = tmp_path / "fresh"
        fresh.mkdir()

        service.apply("legacy", fresh)

        applied = ConfigHandler.load_config(fresh / ".prompticorn" / ".prompticorn.yaml")
        assert applied["version"] == "2.0"
