"""TEMPORARY CI diagnostic for PRO-63 — do not keep.

Rebuilds claude::minimal in the CI environment and, for every file whose
date-normalized content diverges from the committed golden fixture, prints the
path and a repr() of the CI-generated bytes. The assertion message carries the
payload so it shows up in CI logs even without -s.
"""

import json
import re
import tempfile
import unittest
from pathlib import Path

from prompticorn.prompt_builder import get_prompt_builder

_FIXTURE = Path(__file__).parent / "_golden_tool_output.json"
_DATE_RE = re.compile(rb"\d{4}-\d{2}-\d{2}")


def _norm(b: bytes) -> bytes:
    return _DATE_RE.sub(b"YYYY-MM-DD", b)


class TestCiGoldenDiagnostic(unittest.TestCase):
    def test_dump_divergent_files(self) -> None:
        import hashlib

        baseline = json.loads(_FIXTURE.read_text(encoding="utf-8"))
        expected = dict(baseline["claude::minimal"])
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            get_prompt_builder("claude").build(
                root,
                {"spec": {"language": "python"}, "active_personas": ["software_engineer"], "variant": "minimal"},
                dry_run=False,
            )
            report = []
            for path in sorted(root.rglob("*")):
                if not path.is_file():
                    continue
                rel = path.relative_to(root).as_posix()
                raw = path.read_bytes()
                digest = hashlib.sha256(_norm(raw)).hexdigest()
                if expected.get(rel) != digest:
                    report.append(f"\n### DIVERGENT {rel}\nEXPECTED_HASH={expected.get(rel)}\nGOT_HASH={digest}\nGOT_BYTES={_norm(raw)!r}")
                if len(report) >= 2:
                    break
        # Force the payload into the failure output.
        self.assertEqual(report, [], "CI_GOLDEN_DIAGNOSTIC_PAYLOAD" + "".join(report)[:6000])


if __name__ == "__main__":
    unittest.main()
